--- 

- hosts: debian
  strategy: free
  become: yes

  tasks:

    - name: Update packages

      ansible.builtin.apt:
         name: "*"
         state: latest


#    - name: Set authorized key for user ubuntu copying it from current user
#      
#      ansible.posix.authorized_key:
#         user: root
#         state: present
#         key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
